### ISSUE TITLE
python2 back port

### ISSUE THREAD

**Issue by phobrain** [kutoga/going_deeper#1]
ginfty.py:

Added:

from __future__ import print_function

Stuck on this, line 386:

    res = {**res, **res_valid}
            ^
SyntaxError: invalid syntax

**Comment by kutoga** [comment]
Thanks:)

The code should now be fixed, unfortunately I cannot test it here. The following fixes are done:

- Added "from __future__ import print_function"
- Replaced "res = {**res, **res_valid}" by "res.update(res_valid)"

Please let me know if there is still an issue with python2.
